language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
notifications:
  email:
  - tprzepiorka@gmail.com
  - leo.mak@ntlworld.co.uk
  - yxiemeister@googlemail.com
  - masterniket@gmail.com
  - thetmkay@gmail.com
  - mitenmistry3@gmail.com
branches:
  only:
  - production
  - master
deploy:
  provider: heroku
  api_key:
    secure: YQ8IhRPC5O3Zp/WA/aVBUP+UVa4lnvsfnBEIngOdHIruLg08ZFAVhBZlrcf5nWkAQA2ST47W4/lvkGOXxDxVchER9VkHB5nkpFmsZTeOy/+CUpsbA15Z306I7Kc/1CZMWk/DE+avZJ3tdve/DItLp7Xv/dzlkQ6uZ7wS8NbQ+aA=
  app: 
    production: bloomboard
    master: bloomboard-staging
  on:
    repo: thetmkay/bloomboard
