language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
notifications:
  email:
  - tprzepiorka@gmail.com
  - leo.mak@ntlworld.co.uk
  - yxiemeister@googlemail.com
  - masterniket@gmail.com
  - thetmkay@gmail.com
  - mitenmistry3@gmail.com
# only these branches are pushed to travis
branches:
  only:
  - production
  - master
# deploy our app to 2 branches in heroku, one is the cutting-edge build
# and the other is the stable production build
deploy:
  provider: heroku
  app:
    production: bloomboard
    master: bloomboard-staging
  api_key:
    secure: ac5IbVDD4KtoR0UimTy9L8yQqsdKO1MTd9UFcp3Eb3I91cob3yEXgWD2hVWpFmL0Cn9aq2ts23bxEsX7ngEy4urWzQCaHb1e+J2hEoDBgl4OVneFJ51ad+Iiwwi/9ZqgrBRXL4Vsx4aLLZqcQ1cSZd8mA0ek/7TZGkzJJ7YTM64=
